### ISSUE TITLE
Audio Segmentation Issue

### ISSUE THREAD

**Issue by hussainMansoor876** [MTG/essentia.js#106]
## What is the issue about?
- [x] Usage question

## What part(s) of Essentia.js is involved?
- [x] essentia.js-core (vanilla algorithms)
- [ ] essentia.js-model (machine learning algorithms)
- [ ] essentia.js-plot (plotting utility module)
- [ ] essentia.js-extractor (typical algorithm combinations utility)

## Description
... How to get audio segmentation in essentia.js?

## Steps to reproduce / Code snippets / Screenshots
-

## System info 
_i.e. Hardware, OS, platform (which browser / version of Node, etc), Essentia.js version..._
WINDOWS OS
Chrome Browser
essential version 0.1.3

**Comment by jmarcosfer** [comment]
Hi @hussainMansoor876

Not sure what type of segmentation you're after. You could segment by pitch, chords, novelty... All of which are available descriptors/algorithms in Essentia.js. You can compute any of these, and then get timestamps by taking the frame each value was detected on, and converting it to time in seconds. With that you could go back to your audio file and cut it into chunks.

[Here](https://glitch.com/edit/#!/essentiajs-non-rt-worker-segmentation) is a running code example of how to use the NoveltyCurve algorithm, which you could then use to find positions of change in the original audio and do your segmentation (code is in the audio-worker.js script, the main meat is in L42, the `analyse` function).

You can also have a look at our online [onset slicing demo](https://mtg.github.io/essentia.js/examples/demos/onsets/public/), the main code for it is [here](https://github.com/MTG/essentia.js/blob/master/examples/demos/onsets/src/core/audio-worker.js). You will need [these two](https://github.com/MTG/essentia.js/tree/master/examples/demos/onsets/src/core/lib) additional extractors for algorithms we still don't have in the core library.

Hope that helps!
