### ISSUE TITLE
Real-time mood classification - "most" vs "least" danceable part of a track

### ISSUE THREAD

**Issue by highfiiv** [MTG/essentia.js#117]
## What is the issue about?
- [X] Feature request

## Description
I've been researching for how to use Essentia.JS for real-time mood scores but cannot find any direction on this.
More specifically, the [mood classifier](https://mtg.github.io/essentia.js/examples/demos/mood-classifiers/) example shows overall "aggressiveness" score.
However, what about real-time aggressiveness for each moment of the track.

Being able to know which parts of a track is "most" or "least" danceable, aggressive etc. seems a lot more useful than general classification.

Can I get some direction on this usage?

**Comment by albincorreya** [comment]
[This demo](https://github.com/MTG/essentia.js/tree/master/examples/demos/autotagging-rt/src) could be a starting point for real-time use-case (you could also check this [tutorial](https://mtg.github.io/essentia.js/docs/api/tutorial-3.%20Machine%20learning%20inference%20with%20Essentia.js.html#real-time)). 

For this particular mood-classifier demo, the predictions are averaged (check [here](https://github.com/MTG/essentia.js/blob/master/examples/demos/mood-classifiers/src/inference.js#L98)). Model predicts features for every corresponding segment of audio input. ie. It compute mel-spectrogram ([refer](https://github.com/MTG/essentia.js/blob/master/examples/demos/mood-classifiers/src/featureExtraction.js#L18)) for for every frame of audio with a hop-size (if specified) then it feeds to the model for inference, which will return predictions for corresponding to each frame. Note: the audio input is downsampled to 16KHz sample rate, so take that in account when you convert the frames into corresponding timestamps.

Hope that helps.
