### ISSUE TITLE
Is this up-to-date?

### ISSUE THREAD

**Issue by jasongrishkoff** [MTG/essentia.js#127]
Does the NPM/javascript wrapper have the latest C++ code from [the main essentia repository](https://github.com/MTG/essentia)?

**Comment by jmarcosfer** [comment]
Hi!
Not yet, we're currently working on updating the build workflow for Essentia.js, so hopefully we will have an updated build in the coming months. This will also mean you can build locally with the latest Essentia changes provided you have Docker installed. There are, however, [some algorithms](https://github.com/MTG/essentia.js/blob/master/src/python/excluded_algos.md) still not included.

**Comment by jasongrishkoff** [comment]
Great thanks for the heads up! I'll star/watch the main package to stay tuned on updates :)

**Comment by albincorreya** [comment]
@jasongrishkoff  Meanwhile, you could also build the latest changes using docker yourself if needed.

- Clone the essentia.js repo and run the following commands at the project root. (assuming you have docker installed on your system).

```bash
# build essentia with latest master (this might take a few minutes)
docker build -t essentiajs .

# interactive shell inside the container
docker run -it -v `pwd`:/essentia/ essentiajs bash

#  run the build script
./build-libs.sh
```

You will have the latest essentia.js builds in the `dist` directory of your local repo folder.
