### ISSUE TITLE
Chords

### ISSUE THREAD

**Issue by bbevren** [MTG/essentia.js#22]
Hello, lates examples does not include anything about chords...do you have an example or an app whicch dedects chords from mic input?

**Comment by albincorreya** [comment]
Hi @bbevren, 
The chord detection algorithms in Essentia expects a Chroma feature as input. So you need to do the following process chain to compute the chord features

> Audio buffer => Windowing => Spectrum => SpectralPeaks => SpectralWhitening => HPCP => ChordDetection

Check out this basic example https://glitch.com/~essentiajs-simple-chord-detector

Also, check out the [API documentation](https://mtg.github.io/essentia.js/docs/api/Essentia.html) for further tuning these algorithms to your use case.
