### ISSUE TITLE
Node.js example

### ISSUE THREAD

**Issue by CharlesHolbrow** [MTG/essentia.js#44]
Any chance of adding a minimal example for using essentia.js in Node? The main `README.md` says this is possible, but all the examples are written for the browser.

**Comment by jhartquist** [comment]
+1 -- I was also looking for a way to include the TS types in a Node project.

**Comment by sonoalex** [comment]
Here you can find some minimal node examples: [Essentia benchmarks](https://github.com/MTG/essentia.js-benchmarks/blob/master/node/) . Hope it helps!

**Comment by jakiestfu** [comment]
I've been having a hard time getting this to run in a node environment.

```ts
const url = 'https://site.com/song.mp3'

const buffer = await fetch(url)
  .then((r) => r.arrayBuffer())
  .then(Buffer.from)

const results = await essentia.KeyExtractor(essentia.arrayToVector(buffer))
```

This yields the wrong key always. What is the recommended approach to providing the expected data to the API, @sonoalex @albincorreya ?

**Comment by albincorreya** [comment]
@jakiestfu You need to decode the mp3 file buffer into audio data. See some node.js examples with wav files [here](https://github.com/MTG/essentia.js/tree/master/examples/starter-code/nodejs-basic-examples).
 You might need to use external libraries to decode mp3 file (eg: https://github.com/audiojs/audio-decode)

**Comment by jakiestfu** [comment]
Fantastic, @albincorreya Thank you for that reference. Does essentia only support `wav` containers or are other formats supported as well?

**Comment by jakiestfu** [comment]
@albincorreya Would you expect for this to be a correct implementation for a remote resource? I'm still getting incorrect keys and scales for MP3 audio.

```ts
import decodeAudio from 'audio-decode'
import fetch from 'node-fetch'

const main = async () => {
  const url = 'https://site.com/song.mp3'

  const buffer = await fetch(url).then((r) => r.arrayBuffer())
  const decodedAudio = await decodeAudio(buffer)

  const vector = essentia.arrayToVector(decodedAudio._data)

  const { key, scale, strength } = await essentia.KeyExtractor(vector)
}

main()
```

**Comment by silentrob** [comment]
For completion, there are also some examples for Node.js here. [https://github.com/MTG/essentia.js-benchmarks/tree/master/node/benchmark](https://github.com/MTG/essentia.js-benchmarks/tree/master/node/benchmark)

Back to the OP question. I also can't seem to get the KeyExtractor to give me the right key using a WAV or MP3 (node-lame). Based on what some online key detectors say anyway.

**Comment by luciano-work** [comment]
@jakiestfu To get the correct key you need to do this:
```javascript
let esPkg = require('essentia.js');
const essentia = new esPkg.Essentia(esPkg.EssentiaWASM);
const audioBuffer = fs.readFileSync(songFile);
let vectorSignal = essentia.arrayToVector(audioBuffer);
const keyData = essentia.KeyExtractor(vectorSignal, true, 4096, 4096, 12, 3500, 60, 25, 0.2, 'bgate', 16000, 0.0001, 440, 'cosine', 'hann');
const bpm = essentia.PercivalBpmEstimator(vectorSignal, 1024, 2048, 128, 128, 210, 50, 16000).bpm;
console.log(keyData, bpm);
```
