### ISSUE TITLE
Help running example

### ISSUE THREAD

**Issue by willm** [MTG/essentia.js#5]
I'm trying to run the example from the html provided in the readme. Here are the steps I took:

1. Create an `index.html` in the essentia.js directory.
2. Ran`python -m SimpleHTTPServer` in the `essentia.js` directory
3. Open http://localhost:8000 in chrome

I get the following in the console:

![Screenshot from 2019-12-07 09-32-37](https://user-images.githubusercontent.com/771001/70372262-929b3500-18d4-11ea-904e-60692879be10.png)

I tried defining an empty audio buffer by adding the following lines before getting the channel data:

```javascript
var audioCtx = new AudioContext();
var audioBuffer = audioCtx.createBuffer(1, 22050, 22050);
```
However then I get a complaint that `typedFloat32ArrayVec` is not defined. I suspect something has not loaded correctly (This is my first venture into using wasm). I'm also not sure about these errors to `stdio.html`, is there a dependency I'm missing?

**Comment by ljoglar** [comment]
Hi Will,
Sorry I may not be of a lot of help right now (I'm sitting in my plane back from WAC waiting to depart...)
About the complain that `typedFloat32Array2Vec` doesn't exist, did you include the following function in your code?

`<script>
            // sample function to convert javascript float32 typed array to a std::vector<float>
            typedFloat32Array2Vec = function(typedArray) {
                var vec = new Module.VectorFloat();
                for (var i=0; i<typedArray.length; i++) {
                    if (typeof typedArray[i] === 'undefined') {
                        vec.push_back(0);
                    }
                    else {
                        vec.push_back(typedArray[i]);
                    }
                }
                return vec;
            }
      </script>`

**Comment by willm** [comment]
Hi, I think I've got past that problem, the html in the readme defines a function called `typedFloat32Array2Vec` but tries to use it as `typedFloat32ArrayVec` (note the missing 2). So if I create an audio buffer and fix the typo, I get a bit further, but now I get:

![Screenshot from 2019-12-07 10-23-42](https://user-images.githubusercontent.com/771001/70372806-be6de900-18db-11ea-8584-03f936ece689.png)

**Comment by ljoglar** [comment]
Hi Will, I'll look into it.
Thanks.

**Comment by albincorreya** [comment]
Hey @willm, thanks for the feedback. The above-exception was due to the outdated wasm builds. Made a couple of changes in the api as well.  Now it should work as expected. Let me know if not.
