### ISSUE TITLE
Feature Request: MultiPitchKlapuri or MultiPitchMelodia

### ISSUE THREAD

**Issue by VictorSigma** [MTG/essentia.js#6]
There are already many single pitch estimation algorithms on the web but none for multi-pitch detection. If you are thinking about adding any other algorithms soon these two would be good options.

**Comment by albincorreya** [comment]
@VictorSigma Thanks for your feedback. We are currently working on a generic wrapper to bind all the algorithms available in [essentia](https://essentia.upf.edu/) library. All these algorithms will be soon available in essentia.js.

**Comment by JanvyHung** [comment]
> There are already many single pitch estimation algorithms on the web but none for multi-pitch detection. If you are thinking about adding any other algorithms soon these two would be good options.

Hello,excuse me.I am working on the sigle pitch estimation of instruments ,and I have found some  algorithms like YIN. But I am not sure which algorithm is the most effective, so may I have the pleasure of your advice and help? Can you give me some advices which the most effective sigle pitch estimation algorithm, of course , codes or documentations are favorate. Looking forward to your reply. Thank you. Best wishes.

**Comment by dbogdanov** [comment]
@JanvyHung For monophonic signal, try [PitchYin](https://essentia.upf.edu/reference/std_PitchYin.html), [PitchYinFFT](https://essentia.upf.edu/reference/std_PitchYinFFT.html) (less accuracy than PitchYin in low frequencies, but faster),  and [PitchYinProbabilistic](https://essentia.upf.edu/reference/std_PitchYinProbabilistic.html).  All these algorithms should be accessible in essentia.js.

**Comment by albincorreya** [comment]
Since this [PR](https://github.com/MTG/essentia/pull/957) has been merged and also now we have the docker image with the latest upstream Essentia (see this [issue](https://github.com/MTG/essentia.js/issues/25)). These algorithms were added to the upcoming release of the essentia.js. The updates can be found in the `dev` branch. Hence closing this.
