### ISSUE TITLE
Type VectorFLoat?

### ISSUE THREAD

**Issue by Oortone** [MTG/essentia.js#89]
## What is the issue about?
- [ ] Bug
- [ ] Feature request
- [ X] Usage question
- [ ] Documentation
- [ ] Contributing / Development

## What part(s) of Essentia.js is involved?
- [X ] essentia.js-core (vanilla algorithms)
- [ ] essentia.js-model (machine learning algorithms)
- [ ] essentia.js-plot (plotting utility module)
- [ ] essentia.js-extractor (typical algorithm combinations utility)

## Description
New user:
Using the spectrum method I get callbacks with an object just like RMS in the example. However seems I can't acces the bins – in analogy with `ReturnedObject.rms` – using `ReturnedObject.spectrum[1]` for bin 1 and so on. I see the returned object is of type `VectorFloat`. Is this an Essentia type? Or where else can I find information on this type and others non standard Javascript types used? I tried searching.
...

## Steps to reproduce / Code snippets / Screenshots
-

## System info 
_i.e. Hardware, OS, platform (which browser / version of Node, etc), Essentia.js version..._

**Comment by jmarcosfer** [comment]
Hi @Oortone

`VectorFloat`s are an internal type in essentia.js; most algorithms take their input data as `VectorFloat` and output `VectorFloat` if their result is an array of values (as opposed to single-valued outputs, which are inmediately readable in JS). 

Use `essentia.vectorToArray(spectrum)` to convert the spectrum data to a readable format. [Here's the reference](https://mtg.github.io/essentia.js/docs/api/Essentia.html#vectorToArray).

You can also use the following pattern to read directly from the `VectorFloat` without converting. This uses the methods from the `VectorFloat` type itself, which is not super well documented ([see here](https://emscripten.org/docs/porting/connecting_cpp_and_javascript/embind.html#built-in-type-conversions) and [here](https://en.cppreference.com/w/cpp/container/vector): bear in mind that essentia.js is a cross-compilation of the C++ industry standard [Essentia](https://essentia.upf.edu/))
```javascript
for(let i=0; i < spectrum.size(); i++){
    let binData = spectrum.get(i);
    // do whatever you want with the data
}
```

Hope that helps!

**Comment by Oortone** [comment]
Great, I noticed that `get` method but didn't know how to use it.
So basically, when I need to do something _myself_ more than iteration with these vectors, I will need to convert it to Float32array?

**Comment by jmarcosfer** [comment]
Exactly. But if you want to chain several essentia.js algorithms, you don't have to do anything, as they work with `VectorFloat` in and out.
