### ISSUE TITLE
TypeError: 'arguments', 'callee', and 'caller' cannot be accessed in this context

### ISSUE THREAD

**Issue by OlivierEstevez** [MTG/essentia.js#93]
## What is the issue about?
- [ ] Bug
- [ ] Feature request
- [x] Usage question
- [ ] Documentation
- [ ] Contributing / Development

## What part(s) of Essentia.js is involved?
- [x] essentia.js-core (vanilla algorithms)
- [ ] essentia.js-model (machine learning algorithms)
- [ ] essentia.js-plot (plotting utility module)
- [ ] essentia.js-extractor (typical algorithm combinations utility)

## Description
First of all, excuse me for the newbie question. I'm a designer with some Front-End skills, not a professional programmer.
I am making an audio analysis app with React, but I am unable to import Essentia.
Since I'm using React I can not use `let esPkg = require('essentia.js')`, so I ended up importing the packages with the CDN Method. It does work well on Safari, but Chrome gives the following error:
`Uncaught RangeError: WebAssembly.Compile is disallowed on the main thread, if the buffer size is larger than 4KB. Use WebAssembly.compile, or compile on a worker thread.`

I did some research and tried using Web Workers, but I think the easiest way for me is just importing the packages.
Now all the browsers give the following error:
`TypeError: 'arguments', 'callee', and 'caller' cannot be accessed in this context
`
Looks like this functions are deprecated.

## Steps to reproduce / Code snippets / Screenshots
```
import Essentia from "essentia.js/dist/essentia.js-core.es"
import EssentiaWASM from 'essentia.js/dist/essentia-wasm.web.wasm'
import EssentiaWASMWeb from "essentia.js/dist/essentia-wasm.web"
EssentiaWASMWeb(EssentiaWASM)

const instance = new Essentia(EssentiaWASM)
```

## System info 
MacBook Pro M1 Pro, MacOS, Google Chrome: 99.0.4844.51, Node: 16.13.0, Essentia.js: 0.1.3

**Comment by albincorreya** [comment]
For react usage, you can try the ES module imports. See the documentation example [here](https://mtg.github.io/essentia.js/docs/api/tutorial-1.%20Getting%20started.html#es6-style-import). 

The following snippet should work

```javascript

import Essentia from "essentia.js/dist/essentia.js-core.es.js"
import { EssentiaWASM } from "essentia.js/dist/essentia-wasm.web.wasm.es.js"

const essentia = new Essentia(EssentiaWASM);
```
