### ISSUE TITLE
Return object definitions

### ISSUE THREAD

**Issue by Oortone** [MTG/essentia.js#97]
## What is the issue about?
- [ ] Bug
- [ ] Feature request
- [ ] Usage question
- [X] Documentation
- [ ] Contributing / Development

## What part(s) of Essentia.js is involved?
- [X] essentia.js-core (vanilla algorithms)
- [ ] essentia.js-model (machine learning algorithms)
- [ ] essentia.js-plot (plotting utility module)
- [ ] essentia.js-extractor (typical algorithm combinations utility)

## Description
According to documentation, most methods in the Essentia class will return an object where the _data_ from the analysis is enbedded and accessed by one or many `object.data` but how do I know the type of the data? Often I can guess but it's not clear from the documentation, for example a _spectrum_ is possibly the VectorFloat type but a spectrum could also be complex (perhaps not in Essentia I'm not sure this is only an example) in which case I would have a hard time guessing the structure of the return type.

## Steps to reproduce / Code snippets / Screenshots
-

## System info 
not system related, Essentia.js 0.1.3

**Comment by albincorreya** [comment]
You can check the [upstream Essentia documentation](https://essentia.upf.edu/algorithms_reference.html) for the types of output of different algorithms. For example for [Essentia.js RMS](https://mtg.github.io/essentia.js/docs/api/Essentia.html#RMS), you can check [this page](https://essentia.upf.edu/reference/std_RMS.html).
